// AT machine capabilities. Keep slots and base capacities aligned with the block JSON.
export const UPGRADE_PROFILES = {
    "utilitycraft:abyssal_fisher": {
        slots: [3, 4, 5, 6],
        energy_cap: 64000000,
        fluid_cap: 32000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:arcane_enchanter": {
        slots: [8, 9, 10],
        energy_cap: 512000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:arc_press_forge": {
        slots: [12, 13, 14, 15],
        energy_cap: 512000,
        gas_cap: 128000,
        gas_types: 1,
        resource_efficiency: true,
        parallel_slots: 4,
    },
    "utilitycraft:catalyst_weaver": {
        slots: [11, 12, 13, 14],
        energy_cap: 2048000,
        fluid_cap: 512000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:centrifugal_siever": {
        slots: [9, 10, 11, 12],
        energy_cap: 4096000,
        gas_cap: 128000,
        gas_types: 1,
        resource_efficiency: true,
        parallel_slots: 4,
    },
    "utilitycraft:compactor": {
        slots: [12, 13, 14, 15],
        energy_cap: 512000,
        resource_efficiency: true,
    },
    "utilitycraft:cryofluid_synthesizer": {
        slots: [13, 14, 15, 16],
        energy_cap: 512000,
        fluid_cap: 128000,
        fluid_types: 2,
        resource_efficiency: true,
    },
    "utilitycraft:cryo_chamber": {
        slots: [19, 20, 21, 22],
        energy_cap: 1536000,
        fluid_cap: 64000,
        fluid_types: 2,
        resource_efficiency: true,
    },
    "utilitycraft:cryo_freezer": {
        slots: [18, 19, 20, 21],
        energy_cap: 512000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:cryo_stabilizer": {
        slots: [8, 9, 10, 11],
        energy_cap: 512000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:decompactor": {
        slots: [12, 13, 14, 15],
        energy_cap: 512000,
        resource_efficiency: true,
    },
    "utilitycraft:disenchanter": {
        slots: [7, 8, 9],
        energy_cap: 1024000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:dual_siever": {
        slots: [10, 11, 12, 13],
        energy_cap: 8192000,
        gas_cap: 128000,
        gas_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:duplicator": {
        slots: [4, 5, 6, 7],
        energy_cap: 512000000,
        fluid_cap: 512000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:enchantment_station": {
        slots: [19, 20, 21],
        energy_cap: 25600000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:energizer": {
        slots: [5, 6, 7, 8],
        energy_cap: 512000,
        resource_efficiency: true,
    },
    "utilitycraft:genetic_seed_synthesizer": {
        slots: [7, 8, 9, 10],
        energy_cap: 16384000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:impact_crusher": {
        slots: [9, 10, 11, 12],
        energy_cap: 512000,
        fluid_cap: 128000,
        gas_cap: 128000,
        fluid_types: 1,
        gas_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:industrial_burner": {
        slots: [9, 10, 11, 12],
        energy_cap: 1536000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:industrial_crucible": {
        slots: [10, 11, 12, 13],
        energy_cap: 5120000,
        fluid_cap: 128000,
        fluid_types: 1,
        resource_efficiency: true,
        parallel_slots: 6,
    },
    "utilitycraft:laser_barrier": {
        slots: [5],
        energy_cap: 320000,
        resource_efficiency: false,
    },
    "utilitycraft:liquifier": {
        slots: [4, 5, 6, 7],
        energy_cap: 512000,
        fluid_cap: 512000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:pattern_placer": {
        slots: [14, 15, 16],
        energy_cap: 512000,
        resource_efficiency: true,
    },
    "utilitycraft:pulverizer": {
        slots: [12, 13, 14, 15],
        energy_cap: 512000,
        gas_cap: 128000,
        gas_types: 1,
        resource_efficiency: true,
        parallel_slots: 4,
    },
    "utilitycraft:refining_table": {
        slots: [7, 8, 9],
        energy_cap: 32000000,
        fluid_cap: 512000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:reinforcement_anvil": {
        slots: [5, 6, 7],
        energy_cap: 512000,
        resource_efficiency: false,
    },
    "utilitycraft:residue_processor": {
        slots: [4, 5, 6, 7],
        energy_cap: 512000,
        resource_efficiency: true,
    },
    "utilitycraft:seismic_breaker": {
        slots: [6, 7, 8],
        energy_cap: 512000,
        resource_efficiency: false,
    },
    "utilitycraft:singularity_fabricator": {
        slots: [4, 5, 6, 7],
        energy_cap: 1000000000,
        fluid_cap: 1024000,
        fluid_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:vaporworks_processor": {
        slots: [5, 6, 7, 8],
        energy_cap: 512000,
        fluid_cap: 128000,
        gas_cap: 128000,
        fluid_types: 1,
        gas_types: 1,
        resource_efficiency: true,
    },
    "utilitycraft:verdant_cultivator": {
        slots: [8, 9, 10, 11],
        energy_cap: 1024000,
        resource_efficiency: true,
    },
};
