// Generated from UtilityCraft/BP/recipes/compressed/blocks/compress. Do not hand-edit.
// Regenerate from the UtilityCraft source whenever compressed blocks change.
export const UTILITYCRAFT_COMPRESSED_BLOCK_RECIPES = Object.freeze(
[
    [
        "minecraft:amethyst_block",
        "utilitycraft:compressed_amethyst_block"
    ],
    [
        "utilitycraft:compressed_amethyst_block",
        "utilitycraft:compressed_amethyst_block_2"
    ],
    [
        "utilitycraft:compressed_amethyst_block_2",
        "utilitycraft:compressed_amethyst_block_3"
    ],
    [
        "utilitycraft:compressed_amethyst_block_3",
        "utilitycraft:compressed_amethyst_block_4"
    ],
    [
        "minecraft:andesite",
        "utilitycraft:compressed_andesite"
    ],
    [
        "utilitycraft:compressed_andesite",
        "utilitycraft:compressed_andesite_2"
    ],
    [
        "utilitycraft:compressed_andesite_2",
        "utilitycraft:compressed_andesite_3"
    ],
    [
        "utilitycraft:compressed_andesite_3",
        "utilitycraft:compressed_andesite_4"
    ],
    [
        "minecraft:bamboo_block",
        "utilitycraft:compressed_bamboo_block"
    ],
    [
        "utilitycraft:compressed_bamboo_block",
        "utilitycraft:compressed_bamboo_block_2"
    ],
    [
        "utilitycraft:compressed_bamboo_block_2",
        "utilitycraft:compressed_bamboo_block_3"
    ],
    [
        "utilitycraft:compressed_bamboo_block_3",
        "utilitycraft:compressed_bamboo_block_4"
    ],
    [
        "minecraft:basalt",
        "utilitycraft:compressed_basalt"
    ],
    [
        "utilitycraft:compressed_basalt",
        "utilitycraft:compressed_basalt_2"
    ],
    [
        "utilitycraft:compressed_basalt_2",
        "utilitycraft:compressed_basalt_3"
    ],
    [
        "utilitycraft:compressed_basalt_3",
        "utilitycraft:compressed_basalt_4"
    ],
    [
        "minecraft:blackstone",
        "utilitycraft:compressed_blackstone"
    ],
    [
        "utilitycraft:compressed_blackstone",
        "utilitycraft:compressed_blackstone_2"
    ],
    [
        "utilitycraft:compressed_blackstone_2",
        "utilitycraft:compressed_blackstone_3"
    ],
    [
        "utilitycraft:compressed_blackstone_3",
        "utilitycraft:compressed_blackstone_4"
    ],
    [
        "utilitycraft:blaze_block",
        "utilitycraft:compressed_blaze_block"
    ],
    [
        "utilitycraft:compressed_blaze_block",
        "utilitycraft:compressed_blaze_block_2"
    ],
    [
        "utilitycraft:compressed_blaze_block_2",
        "utilitycraft:compressed_blaze_block_3"
    ],
    [
        "utilitycraft:compressed_blaze_block_3",
        "utilitycraft:compressed_blaze_block_4"
    ],
    [
        "utilitycraft:raw_energized_iron_block",
        "utilitycraft:compressed_brute_energized_iron_block"
    ],
    [
        "utilitycraft:compressed_brute_energized_iron_block",
        "utilitycraft:compressed_brute_energized_iron_block_2"
    ],
    [
        "utilitycraft:compressed_brute_energized_iron_block_2",
        "utilitycraft:compressed_brute_energized_iron_block_3"
    ],
    [
        "utilitycraft:compressed_brute_energized_iron_block_3",
        "utilitycraft:compressed_brute_energized_iron_block_4"
    ],
    [
        "utilitycraft:raw_steel_block",
        "utilitycraft:compressed_brute_steel_block"
    ],
    [
        "utilitycraft:compressed_brute_steel_block",
        "utilitycraft:compressed_brute_steel_block_2"
    ],
    [
        "utilitycraft:compressed_brute_steel_block_2",
        "utilitycraft:compressed_brute_steel_block_3"
    ],
    [
        "utilitycraft:compressed_brute_steel_block_3",
        "utilitycraft:compressed_brute_steel_block_4"
    ],
    [
        "minecraft:acacia_wood",
        "utilitycraft:compressed_acacia_wood"
    ],
    [
        "utilitycraft:compressed_acacia_wood",
        "utilitycraft:compressed_acacia_wood_2"
    ],
    [
        "utilitycraft:compressed_acacia_wood_2",
        "utilitycraft:compressed_acacia_wood_3"
    ],
    [
        "utilitycraft:compressed_acacia_wood_3",
        "utilitycraft:compressed_acacia_wood_4"
    ],
    [
        "minecraft:birch_wood",
        "utilitycraft:compressed_birch_wood"
    ],
    [
        "utilitycraft:compressed_birch_wood",
        "utilitycraft:compressed_birch_wood_2"
    ],
    [
        "utilitycraft:compressed_birch_wood_2",
        "utilitycraft:compressed_birch_wood_3"
    ],
    [
        "utilitycraft:compressed_birch_wood_3",
        "utilitycraft:compressed_birch_wood_4"
    ],
    [
        "minecraft:cherry_wood",
        "utilitycraft:compressed_cherry_wood"
    ],
    [
        "utilitycraft:compressed_cherry_wood",
        "utilitycraft:compressed_cherry_wood_2"
    ],
    [
        "utilitycraft:compressed_cherry_wood_2",
        "utilitycraft:compressed_cherry_wood_3"
    ],
    [
        "utilitycraft:compressed_cherry_wood_3",
        "utilitycraft:compressed_cherry_wood_4"
    ],
    [
        "minecraft:crimson_hyphae",
        "utilitycraft:compressed_crimson_wood"
    ],
    [
        "utilitycraft:compressed_crimson_wood",
        "utilitycraft:compressed_crimson_wood_2"
    ],
    [
        "utilitycraft:compressed_crimson_wood_2",
        "utilitycraft:compressed_crimson_wood_3"
    ],
    [
        "utilitycraft:compressed_crimson_wood_3",
        "utilitycraft:compressed_crimson_wood_4"
    ],
    [
        "minecraft:dark_oak_wood",
        "utilitycraft:compressed_dark_oak_wood"
    ],
    [
        "utilitycraft:compressed_dark_oak_wood",
        "utilitycraft:compressed_dark_oak_wood_2"
    ],
    [
        "utilitycraft:compressed_dark_oak_wood_2",
        "utilitycraft:compressed_dark_oak_wood_3"
    ],
    [
        "utilitycraft:compressed_dark_oak_wood_3",
        "utilitycraft:compressed_dark_oak_wood_4"
    ],
    [
        "minecraft:jungle_wood",
        "utilitycraft:compressed_jungle_wood"
    ],
    [
        "utilitycraft:compressed_jungle_wood",
        "utilitycraft:compressed_jungle_wood_2"
    ],
    [
        "utilitycraft:compressed_jungle_wood_2",
        "utilitycraft:compressed_jungle_wood_3"
    ],
    [
        "utilitycraft:compressed_jungle_wood_3",
        "utilitycraft:compressed_jungle_wood_4"
    ],
    [
        "minecraft:mangrove_wood",
        "utilitycraft:compressed_mangrove_wood"
    ],
    [
        "utilitycraft:compressed_mangrove_wood",
        "utilitycraft:compressed_mangrove_wood_2"
    ],
    [
        "utilitycraft:compressed_mangrove_wood_2",
        "utilitycraft:compressed_mangrove_wood_3"
    ],
    [
        "utilitycraft:compressed_mangrove_wood_3",
        "utilitycraft:compressed_mangrove_wood_4"
    ],
    [
        "minecraft:oak_wood",
        "utilitycraft:compressed_oak_wood"
    ],
    [
        "utilitycraft:compressed_oak_wood",
        "utilitycraft:compressed_oak_wood_2"
    ],
    [
        "utilitycraft:compressed_oak_wood_2",
        "utilitycraft:compressed_oak_wood_3"
    ],
    [
        "utilitycraft:compressed_oak_wood_3",
        "utilitycraft:compressed_oak_wood_4"
    ],
    [
        "minecraft:pale_oak_wood",
        "utilitycraft:compressed_pale_oak_wood"
    ],
    [
        "utilitycraft:compressed_pale_oak_wood",
        "utilitycraft:compressed_pale_oak_wood_2"
    ],
    [
        "utilitycraft:compressed_pale_oak_wood_2",
        "utilitycraft:compressed_pale_oak_wood_3"
    ],
    [
        "utilitycraft:compressed_pale_oak_wood_3",
        "utilitycraft:compressed_pale_oak_wood_4"
    ],
    [
        "minecraft:spruce_wood",
        "utilitycraft:compressed_spruce_wood"
    ],
    [
        "utilitycraft:compressed_spruce_wood",
        "utilitycraft:compressed_spruce_wood_2"
    ],
    [
        "utilitycraft:compressed_spruce_wood_2",
        "utilitycraft:compressed_spruce_wood_3"
    ],
    [
        "utilitycraft:compressed_spruce_wood_3",
        "utilitycraft:compressed_spruce_wood_4"
    ],
    [
        "minecraft:warped_hyphae",
        "utilitycraft:compressed_warped_wood"
    ],
    [
        "utilitycraft:compressed_warped_wood",
        "utilitycraft:compressed_warped_wood_2"
    ],
    [
        "utilitycraft:compressed_warped_wood_2",
        "utilitycraft:compressed_warped_wood_3"
    ],
    [
        "utilitycraft:compressed_warped_wood_3",
        "utilitycraft:compressed_warped_wood_4"
    ],
    [
        "minecraft:calcite",
        "utilitycraft:compressed_calcite"
    ],
    [
        "utilitycraft:compressed_calcite",
        "utilitycraft:compressed_calcite_2"
    ],
    [
        "utilitycraft:compressed_calcite_2",
        "utilitycraft:compressed_calcite_3"
    ],
    [
        "utilitycraft:compressed_calcite_3",
        "utilitycraft:compressed_calcite_4"
    ],
    [
        "minecraft:charcoal",
        "utilitycraft:charcoal_block"
    ],
    [
        "utilitycraft:charcoal_block",
        "utilitycraft:compressed_charcoal_block"
    ],
    [
        "utilitycraft:compressed_charcoal_block",
        "utilitycraft:compressed_charcoal_block_2"
    ],
    [
        "utilitycraft:compressed_charcoal_block_2",
        "utilitycraft:compressed_charcoal_block_3"
    ],
    [
        "utilitycraft:compressed_charcoal_block_3",
        "utilitycraft:compressed_charcoal_block_4"
    ],
    [
        "minecraft:clay",
        "utilitycraft:compressed_clay"
    ],
    [
        "utilitycraft:compressed_clay",
        "utilitycraft:compressed_clay_2"
    ],
    [
        "utilitycraft:compressed_clay_2",
        "utilitycraft:compressed_clay_3"
    ],
    [
        "utilitycraft:compressed_clay_3",
        "utilitycraft:compressed_clay_4"
    ],
    [
        "minecraft:coal_block",
        "utilitycraft:compressed_coal_block"
    ],
    [
        "utilitycraft:compressed_coal_block",
        "utilitycraft:compressed_coal_block_2"
    ],
    [
        "utilitycraft:compressed_coal_block_2",
        "utilitycraft:compressed_coal_block_3"
    ],
    [
        "utilitycraft:compressed_coal_block_3",
        "utilitycraft:compressed_coal_block_4"
    ],
    [
        "minecraft:cobbled_deepslate",
        "utilitycraft:compressed_cobbled_deepslate"
    ],
    [
        "utilitycraft:compressed_cobbled_deepslate",
        "utilitycraft:compressed_cobbled_deepslate_2"
    ],
    [
        "utilitycraft:compressed_cobbled_deepslate_2",
        "utilitycraft:compressed_cobbled_deepslate_3"
    ],
    [
        "utilitycraft:compressed_cobbled_deepslate_3",
        "utilitycraft:compressed_cobbled_deepslate_4"
    ],
    [
        "minecraft:cobblestone",
        "utilitycraft:compressed_cobblestone"
    ],
    [
        "minecraft:copper_block",
        "utilitycraft:compressed_copper_block"
    ],
    [
        "utilitycraft:compressed_copper_block",
        "utilitycraft:compressed_copper_block_2"
    ],
    [
        "utilitycraft:compressed_copper_block_2",
        "utilitycraft:compressed_copper_block_3"
    ],
    [
        "utilitycraft:compressed_copper_block_3",
        "utilitycraft:compressed_copper_block_4"
    ],
    [
        "utilitycraft:crushed_blackstone",
        "utilitycraft:compressed_crushed_blackstone"
    ],
    [
        "utilitycraft:compressed_crushed_blackstone",
        "utilitycraft:compressed_crushed_blackstone_2"
    ],
    [
        "utilitycraft:compressed_crushed_blackstone_2",
        "utilitycraft:compressed_crushed_blackstone_3"
    ],
    [
        "utilitycraft:compressed_crushed_blackstone_3",
        "utilitycraft:compressed_crushed_blackstone_4"
    ],
    [
        "utilitycraft:crushed_cobbled_deepslate",
        "utilitycraft:compressed_crushed_cobbled_deepslate"
    ],
    [
        "utilitycraft:compressed_crushed_cobbled_deepslate",
        "utilitycraft:compressed_crushed_cobbled_deepslate_2"
    ],
    [
        "utilitycraft:compressed_crushed_cobbled_deepslate_2",
        "utilitycraft:compressed_crushed_cobbled_deepslate_3"
    ],
    [
        "utilitycraft:compressed_crushed_cobbled_deepslate_3",
        "utilitycraft:compressed_crushed_cobbled_deepslate_4"
    ],
    [
        "utilitycraft:crushed_endstone",
        "utilitycraft:compressed_crushed_endstone"
    ],
    [
        "utilitycraft:compressed_crushed_endstone",
        "utilitycraft:compressed_crushed_endstone_2"
    ],
    [
        "utilitycraft:compressed_crushed_endstone_2",
        "utilitycraft:compressed_crushed_endstone_3"
    ],
    [
        "utilitycraft:compressed_crushed_endstone_3",
        "utilitycraft:compressed_crushed_endstone_4"
    ],
    [
        "utilitycraft:crushed_netherrack",
        "utilitycraft:compressed_crushed_netherrack"
    ],
    [
        "utilitycraft:compressed_crushed_netherrack",
        "utilitycraft:compressed_crushed_netherrack_2"
    ],
    [
        "utilitycraft:compressed_crushed_netherrack_2",
        "utilitycraft:compressed_crushed_netherrack_3"
    ],
    [
        "utilitycraft:compressed_crushed_netherrack_3",
        "utilitycraft:compressed_crushed_netherrack_4"
    ],
    [
        "minecraft:crying_obsidian",
        "utilitycraft:compressed_cry_obsidian"
    ],
    [
        "utilitycraft:compressed_cry_obsidian",
        "utilitycraft:compressed_cry_obsidian_2"
    ],
    [
        "utilitycraft:compressed_cry_obsidian_2",
        "utilitycraft:compressed_cry_obsidian_3"
    ],
    [
        "utilitycraft:compressed_cry_obsidian_3",
        "utilitycraft:compressed_cry_obsidian_4"
    ],
    [
        "minecraft:deepslate",
        "utilitycraft:compressed_deepslate"
    ],
    [
        "utilitycraft:compressed_deepslate",
        "utilitycraft:compressed_deepslate_2"
    ],
    [
        "utilitycraft:compressed_deepslate_2",
        "utilitycraft:compressed_deepslate_3"
    ],
    [
        "utilitycraft:compressed_deepslate_3",
        "utilitycraft:compressed_deepslate_4"
    ],
    [
        "minecraft:diamond_block",
        "utilitycraft:compressed_diamond_block"
    ],
    [
        "utilitycraft:compressed_diamond_block",
        "utilitycraft:compressed_diamond_block_2"
    ],
    [
        "utilitycraft:compressed_diamond_block_2",
        "utilitycraft:compressed_diamond_block_3"
    ],
    [
        "utilitycraft:compressed_diamond_block_3",
        "utilitycraft:compressed_diamond_block_4"
    ],
    [
        "minecraft:diorite",
        "utilitycraft:compressed_diorite"
    ],
    [
        "utilitycraft:compressed_diorite",
        "utilitycraft:compressed_diorite_2"
    ],
    [
        "utilitycraft:compressed_diorite_2",
        "utilitycraft:compressed_diorite_3"
    ],
    [
        "utilitycraft:compressed_diorite_3",
        "utilitycraft:compressed_diorite_4"
    ],
    [
        "minecraft:dirt",
        "utilitycraft:compressed_dirt"
    ],
    [
        "utilitycraft:compressed_dirt",
        "utilitycraft:compressed_dirt_2"
    ],
    [
        "utilitycraft:compressed_dirt_2",
        "utilitycraft:compressed_dirt_3"
    ],
    [
        "utilitycraft:compressed_dirt_3",
        "utilitycraft:compressed_dirt_4"
    ],
    [
        "utilitycraft:compressed_cobblestone",
        "utilitycraft:double_compressed_cobblestone"
    ],
    [
        "minecraft:dripstone_block",
        "utilitycraft:compressed_dripstone_block"
    ],
    [
        "utilitycraft:compressed_dripstone_block",
        "utilitycraft:compressed_dripstone_block_2"
    ],
    [
        "utilitycraft:compressed_dripstone_block_2",
        "utilitycraft:compressed_dripstone_block_3"
    ],
    [
        "utilitycraft:compressed_dripstone_block_3",
        "utilitycraft:compressed_dripstone_block_4"
    ],
    [
        "minecraft:emerald_block",
        "utilitycraft:compressed_emerald_block"
    ],
    [
        "utilitycraft:compressed_emerald_block",
        "utilitycraft:compressed_emerald_block_2"
    ],
    [
        "utilitycraft:compressed_emerald_block_2",
        "utilitycraft:compressed_emerald_block_3"
    ],
    [
        "utilitycraft:compressed_emerald_block_3",
        "utilitycraft:compressed_emerald_block_4"
    ],
    [
        "minecraft:end_stone",
        "utilitycraft:compressed_endstone"
    ],
    [
        "utilitycraft:compressed_endstone",
        "utilitycraft:compressed_endstone_2"
    ],
    [
        "utilitycraft:compressed_endstone_2",
        "utilitycraft:compressed_endstone_3"
    ],
    [
        "utilitycraft:compressed_endstone_3",
        "utilitycraft:compressed_endstone_4"
    ],
    [
        "utilitycraft:energized_iron_block",
        "utilitycraft:compressed_energized_iron_block"
    ],
    [
        "utilitycraft:compressed_energized_iron_block",
        "utilitycraft:compressed_energized_iron_block_2"
    ],
    [
        "utilitycraft:compressed_energized_iron_block_2",
        "utilitycraft:compressed_energized_iron_block_3"
    ],
    [
        "utilitycraft:compressed_energized_iron_block_3",
        "utilitycraft:compressed_energized_iron_block_4"
    ],
    [
        "utilitycraft:flint_block",
        "utilitycraft:compressed_flint_block"
    ],
    [
        "utilitycraft:compressed_flint_block",
        "utilitycraft:compressed_flint_block_2"
    ],
    [
        "utilitycraft:compressed_flint_block_2",
        "utilitycraft:compressed_flint_block_3"
    ],
    [
        "utilitycraft:compressed_flint_block_3",
        "utilitycraft:compressed_flint_block_4"
    ],
    [
        "minecraft:glass",
        "utilitycraft:compressed_glass"
    ],
    [
        "utilitycraft:compressed_glass",
        "utilitycraft:compressed_glass_2"
    ],
    [
        "utilitycraft:compressed_glass_2",
        "utilitycraft:compressed_glass_3"
    ],
    [
        "utilitycraft:compressed_glass_3",
        "utilitycraft:compressed_glass_4"
    ],
    [
        "minecraft:gold_block",
        "utilitycraft:compressed_gold_block"
    ],
    [
        "utilitycraft:compressed_gold_block",
        "utilitycraft:compressed_gold_block_2"
    ],
    [
        "utilitycraft:compressed_gold_block_2",
        "utilitycraft:compressed_gold_block_3"
    ],
    [
        "utilitycraft:compressed_gold_block_3",
        "utilitycraft:compressed_gold_block_4"
    ],
    [
        "minecraft:granite",
        "utilitycraft:compressed_granite"
    ],
    [
        "utilitycraft:compressed_granite",
        "utilitycraft:compressed_granite_2"
    ],
    [
        "utilitycraft:compressed_granite_2",
        "utilitycraft:compressed_granite_3"
    ],
    [
        "utilitycraft:compressed_granite_3",
        "utilitycraft:compressed_granite_4"
    ],
    [
        "minecraft:gravel",
        "utilitycraft:compressed_gravel"
    ],
    [
        "utilitycraft:compressed_gravel",
        "utilitycraft:compressed_gravel_2"
    ],
    [
        "utilitycraft:compressed_gravel_2",
        "utilitycraft:compressed_gravel_3"
    ],
    [
        "utilitycraft:compressed_gravel_3",
        "utilitycraft:compressed_gravel_4"
    ],
    [
        "minecraft:honey_block",
        "utilitycraft:compressed_honey_block"
    ],
    [
        "utilitycraft:compressed_honey_block",
        "utilitycraft:compressed_honey_block_2"
    ],
    [
        "utilitycraft:compressed_honey_block_2",
        "utilitycraft:compressed_honey_block_3"
    ],
    [
        "utilitycraft:compressed_honey_block_3",
        "utilitycraft:compressed_honey_block_4"
    ],
    [
        "minecraft:iron_block",
        "utilitycraft:compressed_iron_block"
    ],
    [
        "utilitycraft:compressed_iron_block",
        "utilitycraft:compressed_iron_block_2"
    ],
    [
        "utilitycraft:compressed_iron_block_2",
        "utilitycraft:compressed_iron_block_3"
    ],
    [
        "utilitycraft:compressed_iron_block_3",
        "utilitycraft:compressed_iron_block_4"
    ],
    [
        "minecraft:lapis_block",
        "utilitycraft:compressed_lapislazuli_block"
    ],
    [
        "utilitycraft:compressed_lapislazuli_block",
        "utilitycraft:compressed_lapislazuli_block_2"
    ],
    [
        "utilitycraft:compressed_lapislazuli_block_2",
        "utilitycraft:compressed_lapislazuli_block_3"
    ],
    [
        "utilitycraft:compressed_lapislazuli_block_3",
        "utilitycraft:compressed_lapislazuli_block_4"
    ],
    [
        "minecraft:oak_log",
        "minecraft:oak_wood"
    ],
    [
        "minecraft:moss_block",
        "utilitycraft:compressed_moss_block"
    ],
    [
        "utilitycraft:compressed_moss_block",
        "utilitycraft:compressed_moss_block_2"
    ],
    [
        "utilitycraft:compressed_moss_block_2",
        "utilitycraft:compressed_moss_block_3"
    ],
    [
        "utilitycraft:compressed_moss_block_3",
        "utilitycraft:compressed_moss_block_4"
    ],
    [
        "minecraft:mud",
        "utilitycraft:compressed_mud"
    ],
    [
        "utilitycraft:compressed_mud",
        "utilitycraft:compressed_mud_2"
    ],
    [
        "utilitycraft:compressed_mud_2",
        "utilitycraft:compressed_mud_3"
    ],
    [
        "utilitycraft:compressed_mud_3",
        "utilitycraft:compressed_mud_4"
    ],
    [
        "minecraft:netherite_block",
        "utilitycraft:compressed_netherite_block"
    ],
    [
        "utilitycraft:compressed_netherite_block",
        "utilitycraft:compressed_netherite_block_2"
    ],
    [
        "utilitycraft:compressed_netherite_block_2",
        "utilitycraft:compressed_netherite_block_3"
    ],
    [
        "utilitycraft:compressed_netherite_block_3",
        "utilitycraft:compressed_netherite_block_4"
    ],
    [
        "minecraft:netherrack",
        "utilitycraft:compressed_netherrack"
    ],
    [
        "utilitycraft:compressed_netherrack",
        "utilitycraft:compressed_netherrack_2"
    ],
    [
        "utilitycraft:compressed_netherrack_2",
        "utilitycraft:compressed_netherrack_3"
    ],
    [
        "utilitycraft:compressed_netherrack_3",
        "utilitycraft:compressed_netherrack_4"
    ],
    [
        "utilitycraft:octuple_compressed_cobblestone",
        "utilitycraft:nonuple_compressed_cobblestone"
    ],
    [
        "minecraft:obsidian",
        "utilitycraft:compressed_obsidian"
    ],
    [
        "utilitycraft:compressed_obsidian",
        "utilitycraft:compressed_obsidian_2"
    ],
    [
        "utilitycraft:compressed_obsidian_2",
        "utilitycraft:compressed_obsidian_3"
    ],
    [
        "utilitycraft:compressed_obsidian_3",
        "utilitycraft:compressed_obsidian_4"
    ],
    [
        "utilitycraft:septuple_compressed_cobblestone",
        "utilitycraft:octuple_compressed_cobblestone"
    ],
    [
        "utilitycraft:triple_compressed_cobblestone",
        "utilitycraft:quadruple_compressed_cobblestone"
    ],
    [
        "minecraft:quartz_block",
        "utilitycraft:compressed_quartz_block"
    ],
    [
        "utilitycraft:compressed_quartz_block",
        "utilitycraft:compressed_quartz_block_2"
    ],
    [
        "utilitycraft:compressed_quartz_block_2",
        "utilitycraft:compressed_quartz_block_3"
    ],
    [
        "utilitycraft:compressed_quartz_block_3",
        "utilitycraft:compressed_quartz_block_4"
    ],
    [
        "utilitycraft:quadruple_compressed_cobblestone",
        "utilitycraft:quintuple_compressed_cobblestone"
    ],
    [
        "minecraft:raw_copper_block",
        "utilitycraft:compressed_raw_copper_block"
    ],
    [
        "utilitycraft:compressed_raw_copper_block",
        "utilitycraft:compressed_raw_copper_block_2"
    ],
    [
        "utilitycraft:compressed_raw_copper_block_2",
        "utilitycraft:compressed_raw_copper_block_3"
    ],
    [
        "utilitycraft:compressed_raw_copper_block_3",
        "utilitycraft:compressed_raw_copper_block_4"
    ],
    [
        "minecraft:raw_gold_block",
        "utilitycraft:compressed_raw_gold_block"
    ],
    [
        "utilitycraft:compressed_raw_gold_block",
        "utilitycraft:compressed_raw_gold_block_2"
    ],
    [
        "utilitycraft:compressed_raw_gold_block_2",
        "utilitycraft:compressed_raw_gold_block_3"
    ],
    [
        "utilitycraft:compressed_raw_gold_block_3",
        "utilitycraft:compressed_raw_gold_block_4"
    ],
    [
        "minecraft:raw_iron_block",
        "utilitycraft:compressed_raw_iron_block"
    ],
    [
        "utilitycraft:compressed_raw_iron_block",
        "utilitycraft:compressed_raw_iron_block_2"
    ],
    [
        "utilitycraft:compressed_raw_iron_block_2",
        "utilitycraft:compressed_raw_iron_block_3"
    ],
    [
        "utilitycraft:compressed_raw_iron_block_3",
        "utilitycraft:compressed_raw_iron_block_4"
    ],
    [
        "minecraft:red_sand",
        "utilitycraft:compressed_red_sand"
    ],
    [
        "utilitycraft:compressed_red_sand",
        "utilitycraft:compressed_red_sand_2"
    ],
    [
        "utilitycraft:compressed_red_sand_2",
        "utilitycraft:compressed_red_sand_3"
    ],
    [
        "utilitycraft:compressed_red_sand_3",
        "utilitycraft:compressed_red_sand_4"
    ],
    [
        "minecraft:redstone_block",
        "utilitycraft:compressed_redstone_block"
    ],
    [
        "utilitycraft:compressed_redstone_block",
        "utilitycraft:compressed_redstone_block_2"
    ],
    [
        "utilitycraft:compressed_redstone_block_2",
        "utilitycraft:compressed_redstone_block_3"
    ],
    [
        "utilitycraft:compressed_redstone_block_3",
        "utilitycraft:compressed_redstone_block_4"
    ],
    [
        "minecraft:sand",
        "utilitycraft:compressed_sand"
    ],
    [
        "utilitycraft:compressed_sand",
        "utilitycraft:compressed_sand_2"
    ],
    [
        "utilitycraft:compressed_sand_2",
        "utilitycraft:compressed_sand_3"
    ],
    [
        "utilitycraft:compressed_sand_3",
        "utilitycraft:compressed_sand_4"
    ],
    [
        "utilitycraft:sextuple_compressed_cobblestone",
        "utilitycraft:septuple_compressed_cobblestone"
    ],
    [
        "utilitycraft:quintuple_compressed_cobblestone",
        "utilitycraft:sextuple_compressed_cobblestone"
    ],
    [
        "utilitycraft:silicon_block",
        "utilitycraft:compressed_silicon_block"
    ],
    [
        "utilitycraft:compressed_silicon_block",
        "utilitycraft:compressed_silicon_block_2"
    ],
    [
        "utilitycraft:compressed_silicon_block_2",
        "utilitycraft:compressed_silicon_block_3"
    ],
    [
        "utilitycraft:compressed_silicon_block_3",
        "utilitycraft:compressed_silicon_block_4"
    ],
    [
        "minecraft:slime",
        "utilitycraft:compressed_slime_block"
    ],
    [
        "utilitycraft:compressed_slime_block",
        "utilitycraft:compressed_slime_block_2"
    ],
    [
        "utilitycraft:compressed_slime_block_2",
        "utilitycraft:compressed_slime_block_3"
    ],
    [
        "utilitycraft:compressed_slime_block_3",
        "utilitycraft:compressed_slime_block_4"
    ],
    [
        "minecraft:soul_sand",
        "utilitycraft:compressed_soul_sand"
    ],
    [
        "utilitycraft:compressed_soul_sand",
        "utilitycraft:compressed_soul_sand_2"
    ],
    [
        "utilitycraft:compressed_soul_sand_2",
        "utilitycraft:compressed_soul_sand_3"
    ],
    [
        "utilitycraft:compressed_soul_sand_3",
        "utilitycraft:compressed_soul_sand_4"
    ],
    [
        "minecraft:soul_soil",
        "utilitycraft:compressed_soul_soil"
    ],
    [
        "utilitycraft:compressed_soul_soil",
        "utilitycraft:compressed_soul_soil_2"
    ],
    [
        "utilitycraft:compressed_soul_soil_2",
        "utilitycraft:compressed_soul_soil_3"
    ],
    [
        "utilitycraft:compressed_soul_soil_3",
        "utilitycraft:compressed_soul_soil_4"
    ],
    [
        "utilitycraft:steel_block",
        "utilitycraft:compressed_steel_block"
    ],
    [
        "utilitycraft:compressed_steel_block",
        "utilitycraft:compressed_steel_block_2"
    ],
    [
        "utilitycraft:compressed_steel_block_2",
        "utilitycraft:compressed_steel_block_3"
    ],
    [
        "utilitycraft:compressed_steel_block_3",
        "utilitycraft:compressed_steel_block_4"
    ],
    [
        "minecraft:stone",
        "utilitycraft:compressed_stone"
    ],
    [
        "utilitycraft:compressed_stone",
        "utilitycraft:compressed_stone_2"
    ],
    [
        "utilitycraft:compressed_stone_2",
        "utilitycraft:compressed_stone_3"
    ],
    [
        "utilitycraft:compressed_stone_3",
        "utilitycraft:compressed_stone_4"
    ],
    [
        "utilitycraft:double_compressed_cobblestone",
        "utilitycraft:triple_compressed_cobblestone"
    ],
    [
        "minecraft:tuff",
        "utilitycraft:compressed_tuff"
    ],
    [
        "utilitycraft:compressed_tuff",
        "utilitycraft:compressed_tuff_2"
    ],
    [
        "utilitycraft:compressed_tuff_2",
        "utilitycraft:compressed_tuff_3"
    ],
    [
        "utilitycraft:compressed_tuff_3",
        "utilitycraft:compressed_tuff_4"
    ]
]
);
