// Generated from UtilityCraft/BP/recipes/compressed/items/*/compress. Do not hand-edit.
export const UTILITYCRAFT_COMPRESSED_ITEM_RECIPES = Object.freeze(
[
    [
        "minecraft:beetroot_seeds",
        "utilitycraft:bag_of_beetroot_seeds",
        9,
        1
    ],
    [
        "minecraft:black_dye",
        "utilitycraft:bag_of_black_dye",
        9,
        1
    ],
    [
        "minecraft:blaze_powder",
        "utilitycraft:bag_of_blaze_powder",
        9,
        1
    ],
    [
        "minecraft:blue_dye",
        "utilitycraft:bag_of_blue_dye",
        9,
        1
    ],
    [
        "minecraft:brown_dye",
        "utilitycraft:bag_of_brown_dye",
        9,
        1
    ],
    [
        "minecraft:cocoa_beans",
        "utilitycraft:bag_of_cocoa_beans",
        9,
        1
    ],
    [
        "minecraft:cyan_dye",
        "utilitycraft:bag_of_cyan_dye",
        9,
        1
    ],
    [
        "minecraft:feather",
        "utilitycraft:bag_of_feathers",
        9,
        1
    ],
    [
        "minecraft:glowstone_dust",
        "utilitycraft:bag_of_glowstone_dust",
        9,
        1
    ],
    [
        "minecraft:gray_dye",
        "utilitycraft:bag_of_gray_dye",
        9,
        1
    ],
    [
        "minecraft:green_dye",
        "utilitycraft:bag_of_green_dye",
        9,
        1
    ],
    [
        "minecraft:gunpowder",
        "utilitycraft:bag_of_gunpowder",
        9,
        1
    ],
    [
        "minecraft:light_blue_dye",
        "utilitycraft:bag_of_light_blue_dye",
        9,
        1
    ],
    [
        "minecraft:light_gray_dye",
        "utilitycraft:bag_of_light_gray_dye",
        9,
        1
    ],
    [
        "minecraft:lime_dye",
        "utilitycraft:bag_of_lime_dye",
        9,
        1
    ],
    [
        "minecraft:magenta_dye",
        "utilitycraft:bag_of_magenta_dye",
        9,
        1
    ],
    [
        "minecraft:melon_seeds",
        "utilitycraft:bag_of_melon_seeds",
        9,
        1
    ],
    [
        "minecraft:orange_dye",
        "utilitycraft:bag_of_orange_dye",
        9,
        1
    ],
    [
        "minecraft:pink_dye",
        "utilitycraft:bag_of_pink_dye",
        9,
        1
    ],
    [
        "minecraft:pitcher_pod",
        "utilitycraft:bag_of_pitcher_pod",
        9,
        1
    ],
    [
        "minecraft:pumpkin_seeds",
        "utilitycraft:bag_of_pumpkin_seeds",
        9,
        1
    ],
    [
        "minecraft:purple_dye",
        "utilitycraft:bag_of_purple_dye",
        9,
        1
    ],
    [
        "minecraft:red_dye",
        "utilitycraft:bag_of_red_dye",
        9,
        1
    ],
    [
        "minecraft:sugar",
        "utilitycraft:bag_of_sugar",
        9,
        1
    ],
    [
        "minecraft:torchflower_seeds",
        "utilitycraft:bag_of_torchflower_seeds",
        9,
        1
    ],
    [
        "minecraft:wheat_seeds",
        "utilitycraft:bag_of_wheat_seeds",
        9,
        1
    ],
    [
        "minecraft:white_dye",
        "utilitycraft:bag_of_white_dye",
        9,
        1
    ],
    [
        "minecraft:yellow_dye",
        "utilitycraft:bag_of_yellow_dye",
        9,
        1
    ],
    [
        "minecraft:blaze_rod",
        "utilitycraft:bundle_of_blaze_rods",
        9,
        1
    ],
    [
        "minecraft:breeze_rod",
        "utilitycraft:bundle_of_breeze_rods",
        9,
        1
    ],
    [
        "minecraft:stick",
        "utilitycraft:bundle_of_sticks",
        9,
        1
    ],
    [
        "minecraft:cookie",
        "utilitycraft:jar_of_cookies",
        9,
        1
    ],
    [
        "minecraft:ghast_tear",
        "utilitycraft:jar_of_ghast_tears",
        9,
        1
    ],
    [
        "minecraft:glow_ink_sac",
        "utilitycraft:jar_of_glow_ink",
        9,
        1
    ],
    [
        "minecraft:ink_sac",
        "utilitycraft:jar_of_ink",
        9,
        1
    ],
    [
        "minecraft:paper",
        "utilitycraft:ream_of_paper",
        6,
        1
    ],
    [
        "minecraft:string",
        "utilitycraft:spool_of_strings",
        9,
        1
    ],
    [
        "minecraft:fermented_spider_eye",
        "utilitycraft:vase_of_fermented_spider_eyes",
        9,
        1
    ],
    [
        "minecraft:spider_eye",
        "utilitycraft:vase_of_spider_eye",
        9,
        1
    ]
]
);
