export const REFINING_TABLE_CONFIG = Object.freeze({
    defaults: Object.freeze({
        idleEnergyCost: 100,
        xpTankCapacity: 512000,
        xpFluidType: 'xp',
        unlockCatalystId: 'utilitycraft:runic_core',
        maxIngotsPerRoll: 8,
        strongThreshold: 0.55,
        masterworkThreshold: 0.78,
        transcendentThreshold: 0.92,
        minRollSpread: 0.3,
    }),
    chips: Object.freeze({
        'utilitycraft:chip': Object.freeze({ id: 'utilitycraft:chip', label: 'Chip', minQuality: 0.08, maxQuality: 0.38, baseXpCost: 80, baseEnergyCost: 5200 }),
        'utilitycraft:basic_chip': Object.freeze({ id: 'utilitycraft:basic_chip', label: 'Basic Chip', minQuality: 0.18, maxQuality: 0.48, baseXpCost: 120, baseEnergyCost: 7600 }),
        'utilitycraft:advanced_chip': Object.freeze({ id: 'utilitycraft:advanced_chip', label: 'Advanced Chip', minQuality: 0.30, maxQuality: 0.62, baseXpCost: 180, baseEnergyCost: 10800 }),
        'utilitycraft:expert_chip': Object.freeze({ id: 'utilitycraft:expert_chip', label: 'Expert Chip', minQuality: 0.42, maxQuality: 0.74, baseXpCost: 260, baseEnergyCost: 15400 }),
        'utilitycraft:ultimate_chip': Object.freeze({ id: 'utilitycraft:ultimate_chip', label: 'Ultimate Chip', minQuality: 0.54, maxQuality: 0.9, baseXpCost: 360, baseEnergyCost: 21200 }),
        'utilitycraft:superior_chip': Object.freeze({ id: 'utilitycraft:superior_chip', label: 'Superior Chip', minQuality: 0.7, maxQuality: 1, baseXpCost: 500, baseEnergyCost: 28600 }),
        'utilitycraft:absolute_chip': Object.freeze({ id: 'utilitycraft:absolute_chip', label: 'Absolute Chip', minQuality: 0.9, maxQuality: 1, baseXpCost: 680, baseEnergyCost: 36800 }),
    }),
    ingots: Object.freeze({
        'minecraft:copper_ingot': Object.freeze({ id: 'minecraft:copper_ingot', label: 'Copper Ingot', power: 0.2 }),
        'minecraft:iron_ingot': Object.freeze({ id: 'minecraft:iron_ingot', label: 'Iron Ingot', power: 0.50 }),
        'minecraft:gold_ingot': Object.freeze({ id: 'minecraft:gold_ingot', label: 'Gold Ingot', power: 0.60 }),
        'utilitycraft:steel_ingot': Object.freeze({ id: 'utilitycraft:steel_ingot', label: 'Steel Ingot', power: 1 }),
        'utilitycraft:energized_iron_ingot': Object.freeze({ id: 'utilitycraft:energized_iron_ingot', label: 'Energized Iron Ingot', power: 2 }),
        'minecraft:diamond': { id: 'minecraft:diamond', label: 'Diamond', power: 2.75 },
        'utilitycraft:titanium': Object.freeze({ id: 'utilitycraft:titanium', label: 'Titanium Ingot', power: 3 }),
        'minecraft:netherite_ingot': Object.freeze({ id: 'minecraft:netherite_ingot', label: 'Netherite Ingot', power: 4 }),
        'utilitycraft:aetherium': Object.freeze({ id: 'utilitycraft:aetherium', label: 'Aetherium Ingot', power: 5 }),
    }),
    templates: Object.freeze({
        weapon: Object.freeze({
            damageMultiplier: 0.10,
            extraDamage: 1.6,
            critChance: 0.05,
            critDamageBonus: 0.24,
            penetration: 0.06,
            lifesteal: 0.018,
            elementalChance: 0.24,
            elementalDamage: 3.2,
        }),
        tool: Object.freeze({
            extraDamage: 0.8,
            bonusDropChance: 0.08,
            oreBonusChance: 0.10,
            durabilitySaveChance: 0.08,
            elementalChance: 0.10,
            elementalDamage: 1.4,
        }),
        hybrid: Object.freeze({
            damageMultiplier: 0.08,
            extraDamage: 1.25,
            critChance: 0.035,
            critDamageBonus: 0.5,
            penetration: 0.05,
            lifesteal: 0.025,
            bonusDropChance: 0.1,
            oreBonusChance: 0.1,
            durabilitySaveChance: 0.2,
            elementalChance: 0.3,
            elementalDamage: 4,
        }),
        support: Object.freeze({
            damageReduction: 0.025,
            durabilityPreserveChance: 0.1,
            negateAllDamageChance: 0.001,
        }),
    }),
    tierScales: Object.freeze({
        wood: 0.2,
        stone: 0.5,
        iron: 0.6,
        golden: 0.75,
        diamond: 0.9,
        netherite: 1.01,
        titanium: 0.98,
        aetherium: 2,
        lucky: 5,
    }),
    elements: Object.freeze({
        plant: Object.freeze({ id: 'plant', label: '\u00a7a\u2620 Poison', weight: 22, damageScale: 0.05, durationTicks: 120, amplifier: 0 }),
        frost: Object.freeze({ id: 'frost', label: '\u00a7b\u2744 Frost', weight: 20, damageScale: 0.07, durationTicks: 90, amplifier: 1 }),
        fire: Object.freeze({ id: 'fire', label: '\u00a7c\u25b2 Fire', weight: 20, damageScale: 0.08, seconds: 4 }),
        lightning: Object.freeze({ id: 'lightning', label: '\u00a7e\u26a1 Lightning', weight: 18, damageScale: 0.09, durationTicks: 60, amplifier: 0 }),
        darkness: Object.freeze({ id: 'darkness', label: '\u00a78\u25c6 Darkness', weight: 20, damageScale: 0.07, durationTicks: 100, amplifier: 0 }),
    }),
})

